// "use client"
import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import SessionProvider from "@/app/SessionProvider"

// import { NextAuthOptions } from 'next-auth'
// import { getServerSession } from 'next-auth'

const dm = DM_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Me Cabs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dm.className}>
      <body
        suppressHydrationWarning={true}
        className="font-body bg-white dark:bg-gray-500 text-black dark:text-white"
      >
        <SessionProvider>
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
